Repository project-lyrics/app-iOS, pull requests merged in 2024-10, with the labels that each got.

#60 Feat/Scrum 176 알림화면 UI 및 로직 초기 구현
  .gitignore
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Modules.swift
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Project+Environment.swift
  Projects/App/Project.swift
  Projects/App/xcconfigs/Shared.xcconfig
  Projects/Core/Network/Interface/Sources/API/FeelinAPI.swift
  Projects/Core/Network/Interface/Sources/DTO/GetNotificationsResponse.swift
  Projects/Core/Network/Interface/Sources/EndPoint/HTTPMethod.swift
  Projects/Domain/Notification/Interface/Sources/Errors/NotificationError.swift
  Projects/Domain/Notification/Interface/Sources/Models/NoteNotification.swift
  Projects/Domain/Notification/Interface/Sources/Models/NotificationType.swift
  Projects/Domain/Notification/Interface/Sources/NotificationRootStore.swift
  Projects/Domain/Notification/Interface/Sources/Services/NotificationAPIService.swift
  Projects/Domain/Notification/Interface/Sources/Services/NotificationPaginationService.swift
  Projects/Domain/Notification/Interface/Sources/UseCases/CheckNotificationUseCase.swift
  Projects/Domain/Notification/Interface/Sources/UseCases/GetNotificationUseCase.swift
  Projects/Domain/Notification/Project.swift
  Projects/Domain/Notification/Sources/NotificationRoot/NotificationRootStore.swift
  Projects/Domain/Notification/Testing/Sources/NotificationTesting.swift
  Projects/Domain/Notification/Tests/Sources/NotificationTests.swift
  Projects/Domain/Project.swift
  Projects/Domain/Sources/DomainExport.swift
  Projects/Feature/Main/Interface/Sources/ViewControllers/NoteNotificationContainerViewController.swift
  Projects/Feature/Main/Interface/Sources/ViewControllers/NoteNotificationPageViewController.swift
  Projects/Feature/Main/Interface/Sources/ViewControllers/NoteNotificationViewController.swift
  Projects/Feature/Main/Interface/Sources/ViewModels/NoteNotificationViewModel.swift
  Projects/Feature/Main/Interface/Sources/Views/Cells+SupplementaryViews/EmptyNotificationCell.swift
  Projects/Feature/Main/Interface/Sources/Views/Cells+SupplementaryViews/NoteNotificationCell.swift
  Projects/Feature/Main/Interface/Sources/Views/NoteNotificationView.swift
  Projects/Shared/DesignSystem/Sources/Views/FeelinPagerTabStrip/ButtonBarView.swift
  Projects/Shared/DesignSystem/Sources/Views/FeelinPagerTabStrip/FeelinButtonBarPagerTabViewController.swift
Labels: feature

#63 Fix/ 홈화면, 노트상세화면, 노트댓글화면 그리고 커뮤니티 메인 화면의 collectionView관련 버그 수정
  Projects/Feature/Home/Example/Sources/SceneDelegate.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/CommunityMainViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/HomeViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/NoteCommentsViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/NoteDetailViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/CommunityMainViewModel.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/NoteCommentsViewModel.swift
  Projects/Feature/Home/Interface/Sources/Views/Cells+SupplementaryViews/CommentCell.swift
  Projects/Feature/Home/Interface/Sources/Views/Cells+SupplementaryViews/CommunityArtistCell.swift
  Projects/Feature/Home/Interface/Sources/Views/Cells+SupplementaryViews/CommunityNoteHeaderView.swift
  Projects/Feature/Home/Interface/Sources/Views/Cells+SupplementaryViews/FavoriteArtistsHeaderView.swift
  Projects/Feature/Home/Interface/Sources/Views/Cells+SupplementaryViews/NoteCell.swift
  Projects/Feature/Home/Interface/Sources/Views/Cells+SupplementaryViews/NoteDetailHeaderView.swift
  Projects/Feature/Home/Interface/Sources/Views/CommunityMainView.swift
  Projects/Feature/Home/Interface/Sources/Views/HomeView.swift
  Projects/Feature/Home/Interface/Sources/Views/NoteCommentsView.swift
  Projects/Feature/Home/Interface/Sources/Views/NoteDetailView.swift
  Projects/Feature/Home/Testing/Sources/DummyArtist.swift
  Projects/Feature/Home/Testing/Sources/MockGetArtistNotesUseCase.swift
  Projects/Feature/Home/Testing/Sources/MockGetNotesUseCase.swift
  Projects/Feature/Home/Testing/Sources/MockGetSongNotesUseCase.swift
Labels: fix

#66 Feature/최초 로그인시 좋아하는 아티스트를 선택할 수 있는 로직 추가
  Projects/Coordinator/Home/Interface/Sources/HomeCoordinatorInterface.swift
  Projects/Coordinator/SearchNote/Interface/Sources/SearchNoteCoordinatorInterface.swift
  Projects/Core/Network/Interface/Sources/Error/FeelinAPIError.swift
  Projects/Core/Network/Sources/NetworkProvider.swift
  Projects/Core/Network/Sources/TokenInterceptor.swift
  Projects/Domain/Artist/Interface/Sources/Services/ArtistAPIService.swift
  Projects/Domain/Artist/Sources/MockArtistAPIService.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/ArtistSelectViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/CommentMenuViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/HomeViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/ArtistSelectViewModel.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/HomeViewModel.swift
  Projects/Feature/Home/Interface/Sources/Views/Cells+SupplementaryViews/CommunityArtistCell.swift
  Projects/Feature/Home/Interface/Sources/Views/Components/FavoriteArtistSelectButton.swift
  Projects/Shared/Util/Sources/Keychain/KeychainError.swift
  Projects/Shared/Util/Sources/Keychain/Model/UserInformation.swift
Labels: feature

#76 Fix, Refactor/ 커스텀 네비게이션 화면 제스쳐 기능 추가, 검색화면 UI 버그 해결, 버튼 성능 개선 & etc..
  Projects/Coordinator/Home/Interface/Sources/HomeCoordinatorInterface.swift
  Projects/Coordinator/MyPage/Interface/Sources/MyPageCoordinatorInterface.swift
  Projects/Coordinator/SearchNote/Interface/Sources/SearchNoteCoordinatorInterface.swift
  Projects/Coordinator/TabBar/Interface/Sources/TabBarCoordinatorInterface.swift
  Projects/Core/Network/Interface/Sources/API/FeelinAPI.swift
  Projects/Core/Network/Interface/Sources/DTO/Response/GetNotificationsResponse.swift
  Projects/Core/Network/Interface/Sources/DTO/Response/UncheckedNotificationResponse.swift
  Projects/Domain/Notification/Interface/Sources/Models/NoteNotification.swift
  Projects/Domain/Notification/Interface/Sources/Models/NotificationType.swift
  Projects/Domain/Notification/Interface/Sources/Services/NotificationAPIService.swift
  Projects/Domain/Notification/Interface/Sources/UseCases/GetHasUncheckedNotificationUseCase.swift
  Projects/Feature/Home/Interface/Sources/Protocols/NoteMusicHandling.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/CommunityMainViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/HomeViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/NoteCommentsViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/NoteDetailViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/NoteNotificationContainerViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/NoteNotificationViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/ReportViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/SearchNoteViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/SearchSongViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/UserLinkedWebViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/CommunityMainViewModel.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/HomeViewModel.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/NoteCommentsViewModel.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/NoteDetailViewModel.swift
  Projects/Feature/Home/Interface/Sources/Views/Cells+SupplementaryViews/NoteNotificationCell.swift
  Projects/Feature/Home/Interface/Sources/Views/Cells+SupplementaryViews/SearchNoteCell.swift
  Projects/Feature/MyPage/Interface/Sources/ViewControllers/DeleteUserViewController.swift
  Projects/Feature/MyPage/Interface/Sources/ViewControllers/EditUserInfoViewController.swift
  Projects/Feature/MyPage/Interface/Sources/ViewControllers/PageControl/BookmarkViewController.swift
  Projects/Feature/MyPage/Interface/Sources/ViewControllers/PageControl/MyNoteViewController.swift
  Projects/Feature/MyPage/Interface/Sources/ViewControllers/ProfileEditViewController.swift
  Projects/Feature/MyPage/Interface/Sources/ViewModels/BookmarkViewModel.swift
  Projects/Feature/MyPage/Interface/Sources/ViewModels/MyNoteViewModel.swift
  Projects/Shared/DesignSystem/Sources/Views/FeelinSearchBar.swift
  Projects/Shared/Util/Sources/ViewControllers/XBarSwipableNavigationController.swift
Labels: fix, enhancement, feature, refactor

#78 Feature, Refactor, Fix 미확인 알림, 알림 API 개인, 전체로 분리 , 첫 방문 유저 API 추가, 노트작성, 노트수정 뷰 수정 작업
  Projects/Coordinator/Home/Interface/Sources/HomeCoordinatorInterface.swift
  Projects/Coordinator/MyPage/Interface/Sources/MyPageCoordinatorInterface.swift
  Projects/Core/Network/Interface/Sources/API/FeelinAPI.swift
  Projects/Core/Network/Interface/Sources/DTO/Response/FirstVisitorResponse.swift
  Projects/Domain/Notification/Interface/Sources/NotificationRootStore.swift
  Projects/Domain/Notification/Interface/Sources/Services/NotificationAPIServiceInterface.swift
  Projects/Domain/Notification/Interface/Sources/UseCases/GetPersonalNotificationUseCase.swift
  Projects/Domain/Notification/Interface/Sources/UseCases/GetPublicNotificationUseCase.swift
  Projects/Domain/Notification/Sources/NotificationRoot/NotificationAPIService.swift
  Projects/Domain/Notification/Sources/NotificationRoot/NotificationRootStore.swift
  Projects/Domain/OAuth/Tests/Sources/KakaoOAuthServiceTests.swift
  Projects/Domain/UserProfile/Interface/Sources/Services/UserProfileAPIServiceInterface.swift
  Projects/Domain/UserProfile/Interface/Sources/UseCase/CheckFirstVisitorUseCase.swift
  Projects/Domain/UserProfile/Sources/UserProfileAPIService.swift
  Projects/Feature/Home/Interface/Sources/Errors/HomeError.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/CommunityMainViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/HomeViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/Note/NoteCommentsViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/Note/NoteDetailViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/Note/NoteMenuViewConroller.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/NoteNotificationPageViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/Notification/NoteNotificationContainerViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/Notification/NoteNotificationPageViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/Notification/NotePersonalNotificationViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/Notification/NotePublicNotificationViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/UserLink/UserLinkedMenuViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/UserLink/UserLinkedWebViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/WritingNote/EditNoteViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/WritingNote/LyricsBackgroundViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/WritingNote/PostNoteViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/WritingNote/SearchSongViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/WritingNote/SearchSongWebViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/CommunityMainViewModel.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/EditNoteViewModel.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/HomeViewModel.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/Notification/NotePersonalNotificationViewModel.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/Notification/NotePublicNotificationViewModel.swift
  Projects/Feature/Home/Interface/Sources/Views/Cells+SupplementaryViews/LyricsBackgroundCollectionViewCell.swift
  Projects/Feature/Home/Interface/Sources/Views/Report/ReportReasonView.swift
  Projects/Feature/Home/Interface/Sources/Views/Report/ReportView.swift
  Projects/Feature/Home/Interface/Sources/Views/SearchNote/SearchMoreFavoriteArtistView.swift
  Projects/Feature/Home/Interface/Sources/Views/SearchNote/SearchNoteView.swift
  Projects/Feature/Home/Interface/Sources/Views/UserLink/UserLinkedMenuItemButton.swift
  Projects/Feature/Home/Interface/Sources/Views/UserLink/UserLinkedMenuView.swift
  Projects/Feature/Home/Interface/Sources/Views/UserLink/UserLinkedWebView.swift
  Projects/Feature/Home/Interface/Sources/Views/WritingNote/LyricsBackgroundView.swift
  Projects/Feature/Home/Interface/Sources/Views/WritingNote/PostSelectButton.swift
  Projects/Feature/Home/Interface/Sources/Views/WritingNote/SearchSongView.swift
  Projects/Feature/Home/Interface/Sources/Views/WritingNote/SearchSongWebView.swift
  Projects/Feature/Home/Interface/Sources/Views/WritingNote/WritingNoteView.swift
  Projects/Feature/MyPage/Interface/Sources/ViewControllers/MyPageViewController.swift
  Projects/Feature/MyPage/Interface/Sources/ViewControllers/PageControl/BookmarkViewController.swift
  Projects/Feature/MyPage/Interface/Sources/ViewControllers/PageControl/MyNoteViewController.swift
  Projects/Feature/MyPage/Interface/Sources/ViewControllers/PageControl/MyPageTabViewController.swift
  Projects/Feature/MyPage/Interface/Sources/ViewModels/MyNoteViewModel.swift
  Projects/Feature/MyPage/Interface/Sources/ViewModels/MyPageViewModel.swift
  Projects/Feature/MyPage/Interface/Sources/Views/MyPageView.swift
  Projects/Feature/Onboarding/Interface/Sources/Components/Login/BalloonView.swift
Labels: fix, feature, refactor
