Repository project-lyrics/app-iOS, pull requests merged in 2024-08, with the labels that each got.

#43 Feat/Scrum 152 게시글 작성 UI 초기 구현
  Projects/Feature/Main/Interface/Sources/ViewControllers/PostNoteViewController.swift
  Projects/Feature/Main/Interface/Sources/ViewModels/PostNoteViewModel.swift
  Projects/Feature/Main/Interface/Sources/Views/Cells/NoteCell.swift
  Projects/Feature/Main/Interface/Sources/Views/PostNoteView.swift
  Projects/Feature/Main/Interface/Sources/Views/PostSelectButton.swift
  Projects/Shared/DesignSystem/Resources/Images.xcassets/Icons/Add.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/Icons/Add.imageset/Icon.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/Icons/Add.imageset/Icon@2x.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/Icons/Add.imageset/Icon@3x.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/Icons/Gallery.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/Icons/Gallery.imageset/Icon.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/Icons/Gallery.imageset/Icon@2x.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/Icons/Gallery.imageset/Icon@3x.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/Icons/Play.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/Icons/Play.imageset/Icon.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/Icons/Play.imageset/Icon@2x.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/Icons/Play.imageset/Icon@3x.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/images/Album.imageset/Album_Image.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/images/Album.imageset/Album_Image@2x.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/images/Album.imageset/Album_Image@3x.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/images/Album.imageset/Contents.json
  Projects/Shared/DesignSystem/Sources/FeelinImages.swift
Labels: feature

#46 Refactor/ FlexLayout의 dependency 문제 해결
  .gitignore
  Cartfile
  Cartfile.resolved
  Projects/App/Project.swift
  Projects/Coordinator/App/Project.swift
  Projects/Coordinator/Main/Project.swift
  Projects/Coordinator/Onboarding/Project.swift
  Projects/Coordinator/Project.swift
  Projects/Coordinator/TabBar/Project.swift
  Projects/Feature/Main/Project.swift
  Projects/Feature/Onboarding/Project.swift
  Projects/Feature/Project.swift
  Projects/Shared/DesignSystem/Project.swift
  Projects/Shared/Project.swift
  Projects/Shared/ThirdPartyLib/Project.swift
  Projects/Shared/Util/Project.swift
  Tuist/ProjectDescriptionHelpers/SPM.swift
Labels: fix

#48 refactor : feelin baseURL 수정
  Projects/Core/Network/Interface/Sources/API/FeelinAPI.swift
Labels: refactor
