Repository project-lyrics/app-iOS, pull requests merged in 2024-11, with the labels that each got.

#81 QA-0.02 커뮤니티 메인화면 UI 수정 및 버그 해결, 노트작성 기능 및 버그 해결
  Projects/Coordinator/Home/Interface/Sources/HomeCoordinatorInterface.swift
  Projects/Core/Network/Interface/Sources/API/FeelinAPI.swift
  Projects/Core/Network/Interface/Sources/DTO/Response/IsFavoriteArtistResponse.swift
  Projects/Domain/Artist/Interface/Sources/Services/ArtistAPIService.swift
  Projects/Domain/Artist/Interface/Sources/UseCase/GetArtistUseCase.swift
  Projects/Domain/Artist/Sources/MockArtistAPIService.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/ArtistSelectViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/CommunityMainViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/HomeViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/MyFavoriteArtistsViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/Note/NoteDetailViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/SearchMoreFavoriteArtistViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/WritingNote/EditNoteViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/WritingNote/PostNoteViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/CommunityMainViewModel.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/HomeViewModel.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/NoteDetailViewModel.swift
  Projects/Feature/Home/Interface/Sources/Views/ArtistSelectView.swift
  Projects/Feature/Home/Interface/Sources/Views/Cells+SupplementaryViews/CommunityArtistCell.swift
  Projects/Feature/Home/Interface/Sources/Views/Cells+SupplementaryViews/CommunityEmptyArtistCell.swift
  Projects/Feature/Home/Interface/Sources/Views/Cells+SupplementaryViews/EmptyArtistCell.swift
  Projects/Feature/Home/Interface/Sources/Views/Cells+SupplementaryViews/EmptySongCell.swift
  Projects/Feature/Home/Interface/Sources/Views/Cells+SupplementaryViews/NoteCell.swift
  Projects/Feature/Home/Interface/Sources/Views/CommunityMainView.swift
  Projects/Feature/Home/Interface/Sources/Views/Components/FavoriteArtistSelectButton.swift
  Projects/Feature/Home/Interface/Sources/Views/SearchNote/SearchMoreFavoriteArtistView.swift
  Projects/Feature/Home/Interface/Sources/Views/SearchNote/SearchNoteView.swift
  Projects/Feature/Home/Interface/Sources/Views/WritingNote/SearchSongView.swift
  Projects/Feature/Home/Interface/Sources/Views/WritingNote/WritingNoteView.swift
  Projects/Shared/Util/Sources/Extensions/Collection+.swift
  Projects/Shared/Util/Sources/Extensions/Combine/UITextField+Combine.swift
Labels: fix, refactor

#82 QA-0.01(4) 노트 작성 / 수정, 마이페이지, 회원 설정 수정
  Projects/Feature/Home/Interface/Sources/ViewControllers/WritingNote/EditNoteViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/WritingNote/PostNoteViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/WritingNote/SearchSongViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/EditNoteViewModel.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/PostNoteViewModel.swift
  Projects/Feature/Home/Interface/Sources/Views/Cells+SupplementaryViews/SongCollectionViewCell.swift
  Projects/Feature/Home/Interface/Sources/Views/WritingNote/WritingNoteView.swift
  Projects/Feature/MyPage/Interface/Sources/ViewControllers/PageControl/MyPageTabViewController.swift
  Projects/Feature/MyPage/Interface/Sources/ViewControllers/SettingViewController.swift
  Projects/Feature/MyPage/Interface/Sources/ViewModels/ProfileEditViewModel.swift
  Projects/Feature/Onboarding/Interface/Sources/ViewModel/ProfileViewModel.swift
Labels: fix

#84 QA-0.01(5) 노트 작성 / 수정 완료 시점, 노트 삭제 시점에 맞춰 노트 리스트 업데이트
  Projects/Coordinator/Home/Interface/Sources/HomeCoordinatorInterface.swift
  Projects/Coordinator/MyPage/Interface/Sources/MyPageCoordinatorInterface.swift
  Projects/Coordinator/SearchNote/Interface/Sources/SearchNoteCoordinatorInterface.swift
  Projects/Domain/Note/Interface/Sources/Model/DeleteNoteResult.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/CommunityMainViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/HomeViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/Note/NoteCommentsViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/Note/NoteDetailViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/WritingNote/EditNoteViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewControllers/WritingNote/PostNoteViewController.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/CommunityMainViewModel.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/HomeViewModel.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/NoteCommentsViewModel.swift
  Projects/Feature/Home/Interface/Sources/ViewModels/NoteDetailViewModel.swift
  Projects/Feature/MyPage/Interface/Sources/ViewControllers/PageControl/BookmarkViewController.swift
  Projects/Feature/MyPage/Interface/Sources/ViewControllers/PageControl/MyNoteViewController.swift
  Projects/Feature/MyPage/Interface/Sources/ViewModels/BookmarkViewModel.swift
  Projects/Feature/MyPage/Interface/Sources/ViewModels/MyNoteViewModel.swift
  Projects/Shared/Util/Sources/Logger/AppLogger.swift
  Projects/Shared/Util/Sources/Logger/LogTag.swift
Labels: refactor

#87 QA-0.01(9) Privacy Manifest 파일 및 설정 추가
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Project+Environment.swift
  Projects/App/Project.swift
  Tuist/ProjectDescriptionHelpers/Target+Templates.swift
Labels: documentation
